# Generated by Django 4.1.4 on 2023-01-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avtofull',
            name='currency',
            field=models.CharField(blank=True, choices=[('€', '€'), ('$', '$'), ('₤', '₤')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='childrenfull',
            name='currency',
            field=models.CharField(blank=True, choices=[('€', '€'), ('$', '$'), ('₤', '₤')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='electronicsfull',
            name='currency',
            field=models.CharField(blank=True, choices=[('€', '€'), ('$', '$'), ('₤', '₤')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='fashionfull',
            name='currency',
            field=models.CharField(blank=True, choices=[('€', '€'), ('$', '$'), ('₤', '₤')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='housegardenfull',
            name='currency',
            field=models.CharField(blank=True, choices=[('€', '€'), ('$', '$'), ('₤', '₤')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='currency',
            field=models.CharField(blank=True, choices=[('€', '€'), ('$', '$'), ('₤', '₤')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='servicesfull',
            name='currency',
            field=models.CharField(blank=True, choices=[('€', '€'), ('$', '$'), ('₤', '₤')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='workfull',
            name='currency',
            field=models.CharField(blank=True, choices=[('€', '€'), ('$', '$'), ('₤', '₤')], max_length=1, null=True),
        ),
    ]
