# Generated by Django 4.1.4 on 2023-01-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_alter_avtofull_currency_alter_childrenfull_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workfull',
            name='sub_category_en',
            field=models.CharField(blank=True, choices=[('Retail | Sales | Procurement', 'Retail | Sales | Procurement'), ('Logistics | Warehouse | Delivery', 'Logistics | Warehouse | Delivery'), ('Construction | finishing works', 'Construction | finishing works'), ('Construction | finishing works', 'Construction | finishing works'), ('Administrative staff | HR | Secretariat', 'Administrative staff | HR | Secretariat'), ('Security | security', 'Security | security'), ('Cleaning | Home staff', 'Cleaning | Home staff'), ('Beauty | Fitness | Sports', 'Beauty | Fitness | Sports'), ('Education | translation', 'Education | translation'), ('Culture | Arts | Entertainment', 'Culture | Arts | Entertainment'), ('Medicine | Pharmacy', 'Medicine | Pharmacy'), ('IT | computers', 'IT | computers'), ('Banking | Finance | Insurance | Jurisprudence', 'Banking | Finance | Insurance | Jurisprudence'), ('Real estate', 'Real estate'), ('Advertising | Design | PR', 'Advertising | Design | PR'), ('Production | Working specialties', 'Production | Working specialties'), ('Work abroad', 'Work abroad'), ('Accounting', 'Accounting'), ('Hotel and restaurant business | Tourism', 'Hotel and restaurant business | Tourism'), ('Service stations | Car washes', 'Service stations | Car washes'), ('Part - time employment', 'Part - time employment'), ('Other occupations', 'Other occupations')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workfull',
            name='sub_category_ru',
            field=models.CharField(blank=True, choices=[('Розничная торговля |Продажи |Приобретение', 'Розничная торговля |Продажи |Приобретение'), ('Логистика |Склад |Доставка', 'Логистика |Склад |Доставка'), ('Строительство |отделка работает', 'Строительство |отделка работает'), ('Строительство |отделка работает', 'Строительство |отделка работает'), ('Административный персонал |HR |Секретариат', 'Административный персонал |HR |Секретариат'), ('Безопасность |безопасность', 'Безопасность |безопасность'), ('Уборка |Домашний персонал', 'Уборка |Домашний персонал'), ('Красота |Фитнес |Спортивный', 'Красота |Фитнес |Спортивный'), ('Образование |перевод', 'Образование |перевод'), ('Культура |Искусство |Развлечения', 'Культура |Искусство |Развлечения'), ('Медицина |Аптека', 'Медицина |Аптека'), ('Это |компьютеры', 'Это |компьютеры'), ('Банковское дело |Финансы |Страхование |Юриспруденция', 'Банковское дело |Финансы |Страхование |Юриспруденция'), ('Недвижимость', 'Недвижимость'), ('Реклама |Дизайн |Премьер -министр', 'Реклама |Дизайн |Премьер -министр'), ('Производство |Рабочие специальности', 'Производство |Рабочие специальности'), ('Работать за границей', 'Работать за границей'), ('Бухгалтерский учет', 'Бухгалтерский учет'), ('Отель и ресторанный бизнес |Туризм', 'Отель и ресторанный бизнес |Туризм'), ('Справочные станции |Автомобильные стирки', 'Справочные станции |Автомобильные стирки'), ('Неполная занятость', 'Неполная занятость'), ('Другие профессии', 'Другие профессии')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workfull',
            name='sub_category_tr',
            field=models.CharField(blank=True, choices=[('Perakende |Satışlar |Satın alma', 'Perakende |Satışlar |Satın alma'), ('Lojistik |Depo |Teslimat', 'Lojistik |Depo |Teslimat'), ('İnşaat |İşleri bitirmek', 'İnşaat |İşleri bitirmek'), ('İnşaat |İşleri bitirmek', 'İnşaat |İşleri bitirmek'), ('İdari Personel |HR |Sekreterlik', 'İdari Personel |HR |Sekreterlik'), ('Güvenlik |güvenlik', 'Güvenlik |güvenlik'), ('Temizlik |Ev personeli', 'Temizlik |Ev personeli'), ('Güzellik |Fitness |Spor Dalları', 'Güzellik |Fitness |Spor Dalları'), ('Eğitim |tercüme', 'Eğitim |tercüme'), ('Kültür |Sanat |Eğlence', 'Kültür |Sanat |Eğlence'), ('Tıp |Eczane', 'Tıp |Eczane'), ('IT |bilgisayar', 'IT |bilgisayar'), ('Bankacılık |Finans |Sigorta |İçtihat', 'Bankacılık |Finans |Sigorta |İçtihat'), ('Emlak', 'Emlak'), ('Reklam |Tasarım |PR', 'Reklam |Tasarım |PR'), ('Üretim |Çalışma Uzmanlıkları', 'Üretim |Çalışma Uzmanlıkları'), ('Yurt dışında çalışmak', 'Yurt dışında çalışmak'), ('Muhasebe', 'Muhasebe'), ('Otel ve Restoran İşletme |Turizm', 'Otel ve Restoran İşletme |Turizm'), ('Servis İstasyonları |Araba Yıkamaları', 'Servis İstasyonları |Araba Yıkamaları'), ('Yarı-zamanlı istihdam', 'Yarı-zamanlı istihdam'), ('Diğer Meslekler', 'Diğer Meslekler')], max_length=255, null=True),
        ),
    ]
