# Generated by Django 4.1.4 on 2023-02-25 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sections', '0003_alter_workfull_sub_category_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeFull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('title_tr', models.CharField(blank=True, max_length=255, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_tr', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.CharField(max_length=1024, verbose_name='The address is')),
                ('price', models.IntegerField(verbose_name='Starting price')),
                ('upload', models.FileField(upload_to='')),
                ('category_en', models.CharField(blank=True, choices=[('Real estate', 'Real estate'), ('Auto', 'Auto'), ('Job', 'Job'), ('Services', 'Services'), ('For kids', 'For kids'), ('Electronics', 'Electronics'), ('House and garden', 'House and garden'), ('Fashion and style', 'Fashion and style')], default=None, max_length=255, null=True)),
                ('category_ru', models.CharField(blank=True, choices=[('Недвижимость', 'Недвижимость'), ('Авто', 'Авто'), ('Работа', 'Работа'), ('Услуги', 'Услуги'), ('Для детей', 'Для детей'), ('Электроника', 'Электроника'), ('Дом и сад', 'Дом и сад'), ('Мода и стиль', 'Мода и стиль')], default=None, max_length=255, null=True)),
                ('category_tr', models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil')], default=None, max_length=255, null=True)),
                ('recommend', models.BooleanField()),
                ('publisher', models.BooleanField()),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('geocode', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(blank=True, choices=[('€', '€'), ('$', '$'), ('₤', '₤')], max_length=1, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FreeFullViewsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('free_full', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sections.freefull')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FreeFullUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploads', models.FileField(upload_to='')),
                ('free_full_upload', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='free_full_upload', to='sections.freefull')),
            ],
        ),
        migrations.CreateModel(
            name='FreeFullFavouritesUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_full', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sections.freefull')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
