# Generated by Django 4.1.4 on 2023-02-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0004_freefull_freefullviewsuser_freefullupload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avtofull',
            name='category_en',
            field=models.CharField(blank=True, choices=[('Real estate', 'Real estate'), ('Auto', 'Auto'), ('Job', 'Job'), ('Services', 'Services'), ('For kids', 'For kids'), ('Electronics', 'Electronics'), ('House and garden', 'House and garden'), ('Fashion and style', 'Fashion and style'), ('Free', 'Free')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='avtofull',
            name='category_ru',
            field=models.CharField(blank=True, choices=[('Недвижимость', 'Недвижимость'), ('Авто', 'Авто'), ('Работа', 'Работа'), ('Услуги', 'Услуги'), ('Для детей', 'Для детей'), ('Электроника', 'Электроника'), ('Дом и сад', 'Дом и сад'), ('Мода и стиль', 'Мода и стиль'), ('Бесплатный', 'Бесплатный')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='avtofull',
            name='category_tr',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil'), ('ücretsiz', 'ücretsiz')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='childrenfull',
            name='category_en',
            field=models.CharField(blank=True, choices=[('Real estate', 'Real estate'), ('Auto', 'Auto'), ('Job', 'Job'), ('Services', 'Services'), ('For kids', 'For kids'), ('Electronics', 'Electronics'), ('House and garden', 'House and garden'), ('Fashion and style', 'Fashion and style'), ('Free', 'Free')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='childrenfull',
            name='category_ru',
            field=models.CharField(blank=True, choices=[('Недвижимость', 'Недвижимость'), ('Авто', 'Авто'), ('Работа', 'Работа'), ('Услуги', 'Услуги'), ('Для детей', 'Для детей'), ('Электроника', 'Электроника'), ('Дом и сад', 'Дом и сад'), ('Мода и стиль', 'Мода и стиль'), ('Бесплатный', 'Бесплатный')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='childrenfull',
            name='category_tr',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil'), ('ücretsiz', 'ücretsiz')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='electronicsfull',
            name='category_en',
            field=models.CharField(blank=True, choices=[('Real estate', 'Real estate'), ('Auto', 'Auto'), ('Job', 'Job'), ('Services', 'Services'), ('For kids', 'For kids'), ('Electronics', 'Electronics'), ('House and garden', 'House and garden'), ('Fashion and style', 'Fashion and style'), ('Free', 'Free')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='electronicsfull',
            name='category_ru',
            field=models.CharField(blank=True, choices=[('Недвижимость', 'Недвижимость'), ('Авто', 'Авто'), ('Работа', 'Работа'), ('Услуги', 'Услуги'), ('Для детей', 'Для детей'), ('Электроника', 'Электроника'), ('Дом и сад', 'Дом и сад'), ('Мода и стиль', 'Мода и стиль'), ('Бесплатный', 'Бесплатный')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='electronicsfull',
            name='category_tr',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil'), ('ücretsiz', 'ücretsiz')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fashionfull',
            name='category_en',
            field=models.CharField(blank=True, choices=[('Real estate', 'Real estate'), ('Auto', 'Auto'), ('Job', 'Job'), ('Services', 'Services'), ('For kids', 'For kids'), ('Electronics', 'Electronics'), ('House and garden', 'House and garden'), ('Fashion and style', 'Fashion and style'), ('Free', 'Free')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fashionfull',
            name='category_ru',
            field=models.CharField(blank=True, choices=[('Недвижимость', 'Недвижимость'), ('Авто', 'Авто'), ('Работа', 'Работа'), ('Услуги', 'Услуги'), ('Для детей', 'Для детей'), ('Электроника', 'Электроника'), ('Дом и сад', 'Дом и сад'), ('Мода и стиль', 'Мода и стиль'), ('Бесплатный', 'Бесплатный')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fashionfull',
            name='category_tr',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil'), ('ücretsiz', 'ücretsiz')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='freefull',
            name='category_en',
            field=models.CharField(blank=True, choices=[('Real estate', 'Real estate'), ('Auto', 'Auto'), ('Job', 'Job'), ('Services', 'Services'), ('For kids', 'For kids'), ('Electronics', 'Electronics'), ('House and garden', 'House and garden'), ('Fashion and style', 'Fashion and style'), ('Free', 'Free')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='freefull',
            name='category_ru',
            field=models.CharField(blank=True, choices=[('Недвижимость', 'Недвижимость'), ('Авто', 'Авто'), ('Работа', 'Работа'), ('Услуги', 'Услуги'), ('Для детей', 'Для детей'), ('Электроника', 'Электроника'), ('Дом и сад', 'Дом и сад'), ('Мода и стиль', 'Мода и стиль'), ('Бесплатный', 'Бесплатный')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='freefull',
            name='category_tr',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil'), ('ücretsiz', 'ücretsiz')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='housegardenfull',
            name='category_en',
            field=models.CharField(blank=True, choices=[('Real estate', 'Real estate'), ('Auto', 'Auto'), ('Job', 'Job'), ('Services', 'Services'), ('For kids', 'For kids'), ('Electronics', 'Electronics'), ('House and garden', 'House and garden'), ('Fashion and style', 'Fashion and style'), ('Free', 'Free')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='housegardenfull',
            name='category_ru',
            field=models.CharField(blank=True, choices=[('Недвижимость', 'Недвижимость'), ('Авто', 'Авто'), ('Работа', 'Работа'), ('Услуги', 'Услуги'), ('Для детей', 'Для детей'), ('Электроника', 'Электроника'), ('Дом и сад', 'Дом и сад'), ('Мода и стиль', 'Мода и стиль'), ('Бесплатный', 'Бесплатный')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='housegardenfull',
            name='category_tr',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil'), ('ücretsiz', 'ücretsiz')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='category_en',
            field=models.CharField(blank=True, choices=[('Real estate', 'Real estate'), ('Auto', 'Auto'), ('Job', 'Job'), ('Services', 'Services'), ('For kids', 'For kids'), ('Electronics', 'Electronics'), ('House and garden', 'House and garden'), ('Fashion and style', 'Fashion and style'), ('Free', 'Free')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='category_ru',
            field=models.CharField(blank=True, choices=[('Недвижимость', 'Недвижимость'), ('Авто', 'Авто'), ('Работа', 'Работа'), ('Услуги', 'Услуги'), ('Для детей', 'Для детей'), ('Электроника', 'Электроника'), ('Дом и сад', 'Дом и сад'), ('Мода и стиль', 'Мода и стиль'), ('Бесплатный', 'Бесплатный')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='realtyfull',
            name='category_tr',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil'), ('ücretsiz', 'ücretsiz')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicesfull',
            name='category_en',
            field=models.CharField(blank=True, choices=[('Real estate', 'Real estate'), ('Auto', 'Auto'), ('Job', 'Job'), ('Services', 'Services'), ('For kids', 'For kids'), ('Electronics', 'Electronics'), ('House and garden', 'House and garden'), ('Fashion and style', 'Fashion and style'), ('Free', 'Free')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicesfull',
            name='category_ru',
            field=models.CharField(blank=True, choices=[('Недвижимость', 'Недвижимость'), ('Авто', 'Авто'), ('Работа', 'Работа'), ('Услуги', 'Услуги'), ('Для детей', 'Для детей'), ('Электроника', 'Электроника'), ('Дом и сад', 'Дом и сад'), ('Мода и стиль', 'Мода и стиль'), ('Бесплатный', 'Бесплатный')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicesfull',
            name='category_tr',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil'), ('ücretsiz', 'ücretsiz')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workfull',
            name='category_en',
            field=models.CharField(blank=True, choices=[('Real estate', 'Real estate'), ('Auto', 'Auto'), ('Job', 'Job'), ('Services', 'Services'), ('For kids', 'For kids'), ('Electronics', 'Electronics'), ('House and garden', 'House and garden'), ('Fashion and style', 'Fashion and style'), ('Free', 'Free')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workfull',
            name='category_ru',
            field=models.CharField(blank=True, choices=[('Недвижимость', 'Недвижимость'), ('Авто', 'Авто'), ('Работа', 'Работа'), ('Услуги', 'Услуги'), ('Для детей', 'Для детей'), ('Электроника', 'Электроника'), ('Дом и сад', 'Дом и сад'), ('Мода и стиль', 'Мода и стиль'), ('Бесплатный', 'Бесплатный')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workfull',
            name='category_tr',
            field=models.CharField(blank=True, choices=[('Emlak', 'Emlak'), ('Oto', 'Oto'), ('İş', 'İş'), ('Hizmetler', 'Hizmetler'), ('Çocuklar için', 'Çocuklar için'), ('Elektronik', 'Elektronik'), ('Ev ve bahçe', 'Ev ve bahçe'), ('Moda ve stil', 'Moda ve stil'), ('ücretsiz', 'ücretsiz')], default=None, max_length=255, null=True),
        ),
    ]
