export const getSubCategoryOptions = category => subCategoryOptions[category]

const subCategoryOptions = {
    realty: [
        {text: 'Apartment', value: 'Apartments'},
        {text: 'House', value: 'House'},
        {text: 'land', value: 'Land'},
        {text: 'Other', value: 'Other'},
    ],
    avto: [
        {text: 'Cars', value: 'Car'},
        {text: 'Other technique', value: 'Other equipment'},
    ],
    work: [
        {text: 'Retail / sales / purchasing', value: 'Retail | Sales | Procurement'}, 
        {text: 'Logistics / Warehouse / Delivery', value: 'Logistics | Warehouse | Delivery'}, 
        {text: 'Construction / finishing works', value: 'Construction | finishing works'}, 
        {text: 'Administrative staff / HR / Secretariat', value: 'Administrative staff | HR | Secretariat'}, 
        {text: 'Security/security', value: 'Security | security'}, 
        {text: 'Cleaning / Home staff', value: 'Cleaning | Home staff'}, 
        {text: 'Beauty / Fitness / Sports', value: 'Beauty | Fitness | Sports'}, 
        {text: 'Education/translation', value: 'Education | translation'},
        {text: 'Culture / Arts / Entertainment', value: 'Culture | Arts | Entertainment'}, 
        {text: 'Medicine / Pharmacy', value: 'Medicine | Pharmacy'}, 
        {text: 'IT / computers', value: 'IT | computers'}, 
        {text: 'Banking /  Finance / Insurance / Jurisprudence', value: 'Banking | Finance | Insurance | Jurisprudence'}, 
        {text: 'Real estate', value: 'Real estate'}, 
        {text: 'Advertising / Design / PR', value: 'Advertising | Design | PR'}, 
        {text: 'Production / Working specialties', value: 'Production | Working specialties'}, 
        {text: 'Work abroad', value: 'Work abroad'}, 
        {text: 'Accounting', value: 'Accounting'}, 
        {text: 'Hotel and restaurant business / Tourism', value: 'Hotel and restaurant business | Tourism'}, 
        {text: 'Service stations / Car washes', value: 'Service stations | Car washes'}, 
        {text: 'Part-time employment', value: 'Part-time employment'}, 
        {text: 'Other occupations', value: 'Other occupations'}, 
    ],
    fashion: [
        {text: "Women's clothing", value: "Women's clothing"},
        {text: "Women's shoes", value: "Women's shoes"},
        {text: "Children's clothes", value: "Children's clothes"},
        {text: "Men's clothing", value: "Men's clothing"},
        {text: "Accessories", value: "Accessories"},
    ],
    children: [
        {text: "Children's clothing", value: 'Baby clothing', categoryName: 'For kids'},
        {text: "Children's shoes", value: "Baby shoes", categoryName: 'For kids'},
        {text: "Baby strollers / Transport", value: "Baby stroller", categoryName: 'For kids'},
        {text: "Children's toys / Furniture", value: "Baby toys | Furniture", categoryName: 'For kids'},
        {text: "Other goods for children", value: "Other baby products", categoryName: 'For kids'},
    ],
    electronics: [
        {text: "Phones and accessories", value: "Phones | Accessories"},
        {text: "Computers / Tablets / Games", value: "Computers | Games"},
        {text: "TV / Photo / Video / Audio", value: "Video | Audio | TV | Photo"},
        {text: "Other technique", value: "Other equipment"},
    ],
    house_garden: [
        {text: "Furniture", value: "Furniture"},
        {text: "Food / Drinks", value: "Food | Drinks"},
        {text: "Garden", value: "Garden"},
        {text: "Interior items", value: "Interior items"},
        {text: "Construction / Renovation", value: "Construction | Renovation"},
        {text: "Other household goods", value: "Other household goods"},
    ],
    services: [
        {text: 'Cleaning', value: 'Cleaning'},
        {text: 'Business', value: 'Business'},
        {text: 'Domestic services', value: 'Domestic services'},
        {text: 'Beauty / Health', value: 'Beauty | Health'},
        {text: 'Education', value: 'Education'},
        {text: 'Transport', value: 'Transport'},
        {text: 'Construction / Repair', value: 'Construction | Repair'},
        {text: 'Other', value: 'Other'},
    ],
}