export const brandList = ['Abadal', 'Abarth', 'Abbott-Detroit', 'ABT', 'AC Cars', 
'Acura', 'Agrale', 'Aiways', 'Aixam', 'Alfa Romeo', 'Alpina', 'Alpine', 
'Alta', 'Alvis', 'AMC', 'AMG', 'Apollo', 'Arash', 'Arcfox', 'Ariel', 'ARO', 
'Arrinera', 'Arrival', 'Artega', 'Ascari', 'Askam', 'Aston Martin', 'Atalanta Motors', 
'Auburn', 'Audi', 'Audi Sport', 'Aurus', 'Austin', 'Autobacs', 'Autobianchi', 'Axon', 'BAC', 
'BAIC Motor', 'Baltijas Džips', 'Baojun', 'BAZ', 'Bentley', 'Berkeley', 'Berliet', 'Bertone', 
'BharatBenz', 'Bitter', 'Bizzarrini', 'BMW', 'Borgward', 'Bowler', 'Brabus', 'Brammo', 
'Brilliance', 'Bristol', 'Bronto', 'Brooke', 'Bufori', 'Bugatti', 'Buick', 'BYD', 'Cadillac', 
'Caparo', 'Carlsson', 'Caterham', 'Changan', 'Changfeng', 'Chery', 'Chevrolet', 'Chrysler', 
'Cisitalia', 'Citroën', 'Cizeta', 'Cole', 'Corre La Licorne', 'Corvette', 'Dacia', 'Daewoo', 
'DAF', 'Daihatsu', 'Daimler', 'Dartz', 'Datsun', 'David Brown', 'De Tomaso', 'Delage', 
'DeLorean (DMC)', 'Detroit Electric', 'Devel Motors', 'Diatto', 'DINA', 'DKW', 'Dodge', 
'Dongfeng', 'Donkervoort', 'Drive eO', 'DS', 'Eagle', 'EDAG', 'Edsel', 'Eicher', 'Elemental', 
'Elfin', 'Elva', 'Englon', 'ERF', 'Eterniti', 'Ё-Auto', '9ff', 'Facel Vega', 'Faraday Future', 
'FAW', 'Ferrari', 'Fiat', 'Fioravanti', 'Fisker', 'Foden Trucks', 'Force Motors', 'Ford', 
'Foton', 'FPV', 'Franklin', 'Freightliner', 'GAC Group', 'Gardner Douglas', 'GAZ', 'Geely', 
'General Motors', 'Genesis', 'Geo', 'Gilbern', 'Gillet', 'Ginetta', 'GMC', 'Golden Dragon', 
'Gonow', 'Great Wall', 'Grinnall', 'GT-R', 'GTA Motor (Spania GTA)', 'Gumpert', 'Hafei', 
'Haima', 'Haval', 'Hawtai', 'Hennessey', 'Hillman', 'Hindustan Motors', 'Hino', 'Hispano-Suiza', 
'Holden', 'Hommell', 'Honda', 'Horch', 'HSV', 'Hudson', 'Hummer', 'Hupmobile', 'Hyundai', 
'IC Bus', 'Infiniti', 'Innocenti', 'Intermeccanica', 'International Harvester', 
'International Trucks', 'Iran Khodro', 'Irizar', 'Isdera', 'Iso Rivolta', 'Isuzu', 
'Iveco', 'JAC', 'Jaguar', 'Jawa', 'JBA', 'Jeep', 'Jensen', 'JMC', 'Kaiser', 'KAMAZ', 
'Karma', 'Keating', 'Kenworth', 'Kia', 'Koenigsegg', 'KTM', 'Lada', 'Lagonda', 'Lamborghini', 
'Lancia', 'Land Rover', 'Landwind', 'Laraki', 'LEVC', 'Lexus', 'Leyland', 'Lifan', 
'Ligier', 'Lincoln', 'Lister', 'Lloyd', 'Lobini', 'Lotus', 'Lucid', 'Luxgen', 'M BMW', 
'Mack', 'Mahindra', 'MAN', 'Mansory', 'Marcos', 'Marlin', 'Maserati', 'Mastretta', 'Maxus', 
'Maybach', 'MAZ', 'Mazda', 'Mazzanti', 'McLaren', 'Melkus', 'Mercedes-Benz', 'Mercury', 
'Merkur', 'MG', 'Microcar', 'Mills Extreme Vehicles', 'Mini', 'Mitsubishi', 'Mitsuoka', 
'MK Sportscars', 'Monteverdi', 'Morgan', 'Morris', 'Moskvich', 'Mosler', 'Mustang', 
'Navistar', 'Nismo', 'Nissan', 'Noble', 'Oldsmobile', 'Oltcit', 'Olympian Motors', 
'Opel', 'OSCA', 'Paccar', 'Pagani', 'Panhard', 'Panoz', 'Pegaso', 'Perodua', 'Peterbilt', 
'Peugeot', 'PGO', 'Pierce-Arrow', 'Pininfarina', 'Plymouth', 'Polestar', 'Pontiac', 
'Porsche', 'Praga', 'Premier', 'Prodrive', 'Proton', 'Qoros', 'Radical Sportscars', 
'RAM', 'Rambler', 'Ranz', 'Renault', 'Rezvani', 'Riley', 'Rimac', 
'Rinspeed', 'Roewe', 'Rolls-Royce', 'Ronart Cars', 'Rosenbauer', 'Rossion', 'Rover', 
'Ruf', 'Saab', 'SAIC Motor', 'SAIPA', 'Saleen', 'Saturn', 'Scania', 'Scion', 'SEAT', 
'Setra', 'Shelby', 'Simca', 'Singer', 'Sisu Auto', 'Škoda', 'Smart', 'Soueast', 'Spirra', 
'Spyker', 'SRT', 'SsangYong', 'SSC', 'Sterling', 'Studebaker', 'Subaru', 'Suffolk', 
'Suzuki', 'Talbot', 'TANK', 'Tata', 'Tatra', 'Tauro Sport Auto', 'TechArt', 'Tesla', 
'Thai Rung', 'Toroidion', 'Toyota', 'Toyota Crown', 'Tramontana', 'Trion', 'Triumph', 
'Troller', 'TVR', 'UAZ', 'UD Trucks', 'Ultima Sports', 'Vandenbrink', 'Vauxhall', 
'Vector Motors', 'Vencer', 'Venturi', 'Venucia', 'Viper', 'Volkswagen', 'Volvo', 
'Vortex', 'W Motors', 'Wanderer', 'Wartburg', 'Western Star', 'Westfield', 'Wiesmann', 
'Willys-Overland', 'Workhorse', 'Wuling', 'XPeng', 'Yulon', 'Yutong', 'Zarooq Motors', 
'Zastava', 'ZAZ', 'Zeekr', 'Zenos', 'Zenvo', 'Zhongtong Bus', 'ZIL', 'Zinoro', 'Zotye']
