from .base_admin import *
from .realty.admin_realty import *
from .avto.admin_avto import *
from .work.admin_work import *
from .children.admin_children import *
from .services.admin_services import *
from .house_garden.admin_house_garden import *
from .fashion.admin_fashion import *
from .electronics.models_electronics import *
from .free.admin_free import *
